--DROP TABLE VENTAS

--CREATE TABLE VENTAS
--(
--    ID_VENTA INTEGER NOT NULL,
--   FECHA DATE,
--    PRODUCTO VARCHAR(50),
--     CANTIDAD INTEGER,
--     PRECIO_UNITARIO DECIMAL(10,2),
--     CLIENTE VARCHAR(50),
--     CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTA)
-- );

-- CREATE UNIQUE INDEX IDX_CLIENTE ON VENTAS (CLIENTE);

-- INSERT INTO VENTAS
--     (ID_VENTA, FECHA, PRODUCTO, CANTIDAD, PRECIO_UNITARIO, CLIENTE)
-- VALUES
--     (1, '2024-01-10', 'Portatil Lenovo',
--         1, 750.00, 'Maria Gomez');

-- INSERT INTO VENTAS
--     (ID_VENTA, FECHA, PRODUCTO, CANTIDAD, PRECIO_UNITARIO, CLIENTE)
-- VALUES
--     (2, '2024-01-15', 'Raton Logitech',
--         2, 25.00, 'Luis Torres');

-- INSERT INTO VENTAS
--     (ID_VENTA, FECHA, PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
-- VALUES
--     (3, '2023-12-20', 'Teclado mecanico',
--         1, 85.00);

-- INSERT INTO VENTAS
--     (ID_VENTA, FECHA, PRODUCTO, CANTIDAD, PRECIO_UNITARIO, CLIENTE)
-- VALUES
--     (4, '2022-11-10', 'Monitor 24 pulgadas',
--         1, 150.00, 'Maria Gomez');

-- INSERT INTO VENTAS
--     (ID_VENTA, FECHA, PRODUCTO, CANTIDAD, PRECIO_UNITARIO, CLIENTE)
-- VALUES
--     (5, '2024-02-01', 'Portatil HP',
--         1, 820.00, 'Luis Torres');

-- UPDATE VENTAS SET PRECIO_UNITARIO = PRECIO_UNITARIO * 1.05 
-- WHERE YEAR(FECHA) = 2024;

-- DELETE FROM VENTAS WHERE FECHA >= '2023-01-01';

-- ALTER TABLE VENTAS ADD TOTAL_UNIT DECIMAL(10,2);

-- --UPDATE VENTAS SET TOTAL_UNIT = CANTIDAD * PRECIO_UNITARIO;

-- SELECT *
-- FROM VENTAS
-- WHERE CLIENTE = 'Maria Gomez';

-- SELECT *
-- FROM VENTAS
-- --WHERE TOTAL_UNIT > 90 AND TOTAL_UNIT < 100;

-- SELECT *
-- FROM VENTAS
-- WHERE PRODUCTO LIKE '%portatil%';

-- SELECT *
-- FROM VENTAS
-- WHERE CLIENTE IS NULL OR CLIENTE = '';

-- SELECT *, COUNT(*) AS N_VENTAS
-- FROM VENTAS
-- GROUP BY PRODUCTO
-- ORDER BY N_VENTAS;

-- --SELECT CLIENTE, AVG(TOTAL_UNIT) AS TOTAL_PROMEDIO
-- --FROM VENTAS
-- --GROUP BY CLIENTE;

-- SELECT CLIENTE, COUNT(*) AS TOTAL
-- FROM VENTAS
-- GROUP BY CLIENTE
-- HAVING COUNT(*) > 1
-- ORDER BY CLIENTE;

-- SELECT CLIENTE,
--     SUM(CANTIDAD * PRECIO_UNITARIO) AS TOTAL_GASTADO
-- FROM VENTAS
-- GROUP BY CLIENTE
-- HAVING SUM(CANTIDAD * PRECIO_UNITARIO) > 800;

-- SELECT *
-- FROM VENTAS
-- WHERE PRODUCTO <> 'raton';

-- SELECT *
-- FROM VENTAS
-- WHERE PRODUCTO LIKE 'T%';

-- SELECT *
-- FROM VENTAS
-- WHERE PRECIO_UNITARIO >= 100 AND CANTIDAD < 2;

-- --SELECT ID_VENTA, SUBSTR(PRODUCTO, 1, 3)
-- --FROM VENTAS;

-- SELECT *,
--     (CANTIDAD * PRECIO_UNITARIO) AS TOTAL
-- FROM VENTAS
-- ORDER BY 
--     TOTAL DESC

-- SELECT *, SUM(CANTIDAD * PRECIO_UNITARIO) AS TOTAL
-- FROM VENTAS
-- GROUP BY PRODUCTO;

-- SELECT *,
--     SUM(CANTIDAD * PRECIO_UNITARIO) AS TOTAL_GASTADO
-- FROM VENTAS
-- HAVING SUM(CANTIDAD * PRECIO_UNITARIO) > AVG(CANTIDAD * PRECIO_UNITARIO);

-- SELECT PRODUCTO, COUNT(*) AS TOTAL
-- FROM VENTAS
-- GROUP BY PRODUCTO
-- HAVING COUNT(*) > 1
-- ORDER BY PRODUCTO;

-- SELECT *
-- FROM VENTAS
-- WHERE CLIENTE LIKE '%Gomez%';

-- SELECT *
-- FROM VENTAS
-- WHERE CANTIDAD BETWEEN 1 AND 2

-- SELECT *
-- FROM VENTAS
-- WHERE PRODUCTO IN ('Raton Logitech', 'Teclado mecanico');

-- SELECT *
-- FROM VENTAS
-- WHERE (PRECIO_UNITARIO * CANTIDAD) <> 750;

-- SELECT ID_VENTA, PRODUCTO
-- FROM VENTAS
-- WHERE CLIENTE <> 'Luis Torres';

-- SELECT CLIENTE, (PRECIO_UNITARIO * CANTIDAD) AS TOTAL
-- FROM VENTAS
-- GROUP BY CLIENTE;

-- SELECT *
-- FROM VENTAS
-- HAVING COUNT(*) > 15;

-- SELECT ID_VENTA, PRODUCTO, (PRECIO_UNITARIO * CANTIDAD) 
-- AS TOTAL_CALCULADO
-- FROM VENTAS;
