DROP TABLE VENTAS
DROP TABLE PRODUCTOS

CREATE TABLE PRODUCTOS
(
    ID_PRODUCTO INTEGER NOT NULL,
    NOMBRE VARCHAR(50),
    CATEGORIA VARCHAR(50),
    STOCK INTEGER,
    PRECIO DECIMAL(10,2),
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE VENTAS
(
    ID_VENTA INTEGER NOT NULL,
    ID_PRODUCTO INTEGER NOT NULL,
    FECHA_VENTA DATE,
    CANTIDAD INTEGER,
    CLIENTE VARCHAR(50),
    CONSTRAINT PK_VENTAS PRIMARY KEY (ID_VENTA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

---------------------------------------------------
--   P R O D U C T O S     I N S E R T A D O S   --
---------------------------------------------------

INSERT INTO PRODUCTOS
    (ID_PRODUCTO, NOMBRE, CATEGORIA, STOCK, PRECIO)
VALUES
    (1, 'PORTATIL', 'INFORMATICA', 159, 1200.00);

INSERT INTO PRODUCTOS
    (ID_PRODUCTO, NOMBRE, CATEGORIA, STOCK, PRECIO)
VALUES
    (2, 'RATON', 'INFORMATICA', 359, 12.00);

INSERT INTO PRODUCTOS
    (ID_PRODUCTO, NOMBRE, CATEGORIA, STOCK, PRECIO)
VALUES
    (3, 'TECLADO', 'INFORMATICA', 259, 30.00);

INSERT INTO PRODUCTOS
    (ID_PRODUCTO, NOMBRE, CATEGORIA, STOCK, PRECIO)
VALUES
    (4, 'GRAFICA', 'GAMING', 170, 300.00);

INSERT INTO PRODUCTOS
    (ID_PRODUCTO, NOMBRE, CATEGORIA, STOCK, PRECIO)
VALUES
    (5, 'MONITOR', 'GAMING', 90, 100.00);

---------------------------------------------------
--      V E N T A S    I N S E R T A D O S       --
---------------------------------------------------

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (1, 4, '10-05-2025', 2, 'JOSELITO');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (2, 1, '10-05-2010', 1, 'JOSE LUIS');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (3, 3, '01-07-1990', 5, 'JOSE LUIS');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (4, 2, '10-05-2020', 5, 'PEPITO');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (5, 1, '03-09-2025', 21, 'JAIMITO');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (6, 2, '01-01-2025', 60, 'PACO');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (7, 3, '10-01-2024', 2, 'ELVA GINON');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (8, 2, '01-09-2000', 9, 'DOLOES DE HUESO');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (9, 4, '22-12-2005', 1, 'JOSELITO');

INSERT INTO VENTAS
    (ID_VENTA, ID_PRODUCTO, FECHA_VENTA, CANTIDAD, CLIENTE)
VALUES
    (10, 2, '01-05-2011', 1, 'JOSELITO');

SELECT P.NOMBRE, SUM(V.CANTIDAD) AS TOTAL_VENDIDO
FROM PRODUCTOS P JOIN VENTAS V ON P.ID_PRODUCTO = V.ID_PRODUCTO
GROUP BY P.NOMBRE;

SELECT P.ID_PRODUCTO, P.NOMBRE
FROM PRODUCTOS P LEFT JOIN VENTAS V ON P.ID_PRODUCTO = V.ID_PRODUCTO
WHERE V.ID_PRODUCTO IS NULL;

SELECT V.FECHA_VENTA, P.NOMBRE AS PRODUCTO
FROM PRODUCTOS P JOIN VENTAS V ON P.ID_PRODUCTO = V.ID_PRODUCTO
WHERE P.CATEGORIA = 'INFORMATICA'
    AND V.FECHA_VENTA >= '2024-01-01'
    AND V.FECHA_VENTA < '2024-02-01';

SELECT P.NOMBRE AS PRODUCTO, SUM(V.CANTIDAD) AS TOTAL_CANTIDAD,
    P.PRECIO, SUM(V.CANTIDAD * P.PRECIO) AS TOTAL_VENDIDO
FROM PRODUCTOS P JOIN VENTAS V ON P.ID_PRODUCTO = V.ID_PRODUCTO
GROUP BY P.NOMBRE, P.PRECIO;

SELECT V.CLIENTE, P.ID_PRODUCTO, P.NOMBRE AS PRODUCTO, COUNT(*) AS VECES_COMPRADO
FROM VENTAS V JOIN PRODUCTOS P ON V.ID_PRODUCTO = P.ID_PRODUCTO
GROUP BY V.CLIENTE, P.NOMBRE, P.ID_PRODUCTO
HAVING COUNT(*) > 1;
























